# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BetaApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BetaApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BetaApi }) = "http://localhost:6333"

const _returntypes_clear_issues_BetaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Bool,
    Regex("^" * replace("4XX", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_clear_issues(_api::BetaApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_clear_issues_BetaApi, "/issues", ["api-key", "bearerAuth", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Clear issues

Removes all issues reported so far

Params:

Return: Bool, OpenAPI.Clients.ApiResponse
"""
function clear_issues(_api::BetaApi; _mediaType=nothing)
    _ctx = _oacinternal_clear_issues(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function clear_issues(_api::BetaApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_clear_issues(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_issues_BetaApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
    Regex("^" * replace("4XX", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_get_issues(_api::BetaApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_issues_BetaApi, "/issues", ["api-key", "bearerAuth", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get issues

Get a report of performance issues and configuration suggestions

Params:

Return: Any, OpenAPI.Clients.ApiResponse
"""
function get_issues(_api::BetaApi; _mediaType=nothing)
    _ctx = _oacinternal_get_issues(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_issues(_api::BetaApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_issues(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export clear_issues
export get_issues
