# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""TrackerStatus
Represents the current state of the optimizer being tracked

    QdrantTrackerStatus(; value=nothing)
"""
mutable struct QdrantTrackerStatus <: OpenAPI.OneOfAPIModel
    value::Any # Union{ QdrantTrackerStatusOneOf, QdrantTrackerStatusOneOf1, String }
    QdrantTrackerStatus() = new()
    QdrantTrackerStatus(value) = new(value)
end # type QdrantTrackerStatus

function OpenAPI.property_type(::Type{ QdrantTrackerStatus }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantTrackerStatus, name)
end
