# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SparseVectorParams
Params of single sparse vector data storage

    QdrantSparseVectorParams(;
        index=nothing,
    )

    - index::QdrantSparseIndexParams
"""
Base.@kwdef mutable struct QdrantSparseVectorParams <: OpenAPI.APIModel
    index = nothing # spec type: Union{ Nothing, QdrantSparseIndexParams }

    function QdrantSparseVectorParams(index, )
        OpenAPI.validate_property(QdrantSparseVectorParams, Symbol("index"), index)
        return new(index, )
    end
end # type QdrantSparseVectorParams

const _property_types_QdrantSparseVectorParams = Dict{Symbol,String}(Symbol("index")=>"QdrantSparseIndexParams", )
OpenAPI.property_type(::Type{ QdrantSparseVectorParams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantSparseVectorParams[name]))}

function check_required(o::QdrantSparseVectorParams)
    true
end

function OpenAPI.validate_property(::Type{ QdrantSparseVectorParams }, name::Symbol, val)
end
