# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ClusterOperations

    QdrantClusterOperations(; value=nothing)
"""
mutable struct QdrantClusterOperations <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantAbortTransferOperation, QdrantCreateShardingKeyOperation, QdrantDropReplicaOperation, QdrantDropShardingKeyOperation, QdrantMoveShardOperation, QdrantReplicateShardOperation }
    QdrantClusterOperations() = new()
    QdrantClusterOperations(value) = new(value)
end # type QdrantClusterOperations

function OpenAPI.property_type(::Type{ QdrantClusterOperations }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantClusterOperations, name)
end
