# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""VectorStorageType
Storage types for vectors

    QdrantVectorStorageType(; value=nothing)
"""
mutable struct QdrantVectorStorageType <: OpenAPI.OneOfAPIModel
    value::Any # Union{ String }
    QdrantVectorStorageType() = new()
    QdrantVectorStorageType(value) = new(value)
end # type QdrantVectorStorageType

function OpenAPI.property_type(::Type{ QdrantVectorStorageType }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantVectorStorageType, name)
end
