# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""QueryRequestBatch

    QdrantQueryRequestBatch(;
        searches=nothing,
    )

    - searches::Vector{QdrantQueryRequest}
"""
Base.@kwdef mutable struct QdrantQueryRequestBatch <: OpenAPI.APIModel
    searches::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantQueryRequest} }

    function QdrantQueryRequestBatch(searches, )
        OpenAPI.validate_property(QdrantQueryRequestBatch, Symbol("searches"), searches)
        return new(searches, )
    end
end # type QdrantQueryRequestBatch

const _property_types_QdrantQueryRequestBatch = Dict{Symbol,String}(Symbol("searches")=>"Vector{QdrantQueryRequest}", )
OpenAPI.property_type(::Type{ QdrantQueryRequestBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantQueryRequestBatch[name]))}

function check_required(o::QdrantQueryRequestBatch)
    o.searches === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantQueryRequestBatch }, name::Symbol, val)
end
