# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ExtendedPointId
Type, used for specifying point ID in user interface

    QdrantExtendedPointId(; value=nothing)
"""
mutable struct QdrantExtendedPointId <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    QdrantExtendedPointId() = new()
    QdrantExtendedPointId(value) = new(value)
end # type QdrantExtendedPointId

function OpenAPI.property_type(::Type{ QdrantExtendedPointId }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantExtendedPointId, name)
end
