# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ErrorResponse_status

    QdrantErrorResponseStatus(;
        error=nothing,
    )

    - error::String : Description of the occurred error.
"""
Base.@kwdef mutable struct QdrantErrorResponseStatus <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing

    function QdrantErrorResponseStatus(error, )
        OpenAPI.validate_property(QdrantErrorResponseStatus, Symbol("error"), error)
        return new(error, )
    end
end # type QdrantErrorResponseStatus

const _property_types_QdrantErrorResponseStatus = Dict{Symbol,String}(Symbol("error")=>"String", )
OpenAPI.property_type(::Type{ QdrantErrorResponseStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantErrorResponseStatus[name]))}

function check_required(o::QdrantErrorResponseStatus)
    true
end

function OpenAPI.validate_property(::Type{ QdrantErrorResponseStatus }, name::Symbol, val)
end
