# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OverwritePayloadOperation

    QdrantOverwritePayloadOperation(;
        overwrite_payload=nothing,
    )

    - overwrite_payload::QdrantSetPayload
"""
Base.@kwdef mutable struct QdrantOverwritePayloadOperation <: OpenAPI.APIModel
    overwrite_payload = nothing # spec type: Union{ Nothing, QdrantSetPayload }

    function QdrantOverwritePayloadOperation(overwrite_payload, )
        OpenAPI.validate_property(QdrantOverwritePayloadOperation, Symbol("overwrite_payload"), overwrite_payload)
        return new(overwrite_payload, )
    end
end # type QdrantOverwritePayloadOperation

const _property_types_QdrantOverwritePayloadOperation = Dict{Symbol,String}(Symbol("overwrite_payload")=>"QdrantSetPayload", )
OpenAPI.property_type(::Type{ QdrantOverwritePayloadOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantOverwritePayloadOperation[name]))}

function check_required(o::QdrantOverwritePayloadOperation)
    o.overwrite_payload === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantOverwritePayloadOperation }, name::Symbol, val)
end
