# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BoolIndexParams

    QdrantBoolIndexParams(;
        type=nothing,
    )

    - type::QdrantBoolIndexType
"""
Base.@kwdef mutable struct QdrantBoolIndexParams <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, QdrantBoolIndexType }

    function QdrantBoolIndexParams(type, )
        OpenAPI.validate_property(QdrantBoolIndexParams, Symbol("type"), type)
        return new(type, )
    end
end # type QdrantBoolIndexParams

const _property_types_QdrantBoolIndexParams = Dict{Symbol,String}(Symbol("type")=>"QdrantBoolIndexType", )
OpenAPI.property_type(::Type{ QdrantBoolIndexParams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantBoolIndexParams[name]))}

function check_required(o::QdrantBoolIndexParams)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantBoolIndexParams }, name::Symbol, val)
end
