# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Indexes
Vector index configuration

    QdrantIndexes(; value=nothing)
"""
mutable struct QdrantIndexes <: OpenAPI.OneOfAPIModel
    value::Any # Union{ QdrantIndexesOneOf, QdrantIndexesOneOf1 }
    QdrantIndexes() = new()
    QdrantIndexes(value) = new(value)
end # type QdrantIndexes

function OpenAPI.property_type(::Type{ QdrantIndexes }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantIndexes, name)
end
