# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Match
Match filter request

    QdrantMatch(; value=nothing)
"""
mutable struct QdrantMatch <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantMatchAny, QdrantMatchExcept, QdrantMatchText, QdrantMatchValue }
    QdrantMatch() = new()
    QdrantMatch(value) = new(value)
end # type QdrantMatch

function OpenAPI.property_type(::Type{ QdrantMatch }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantMatch, name)
end
