# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""collection_exists_200_response

    QdrantCollectionExists200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantCollectionExistence
"""
Base.@kwdef mutable struct QdrantCollectionExists200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantCollectionExistence }

    function QdrantCollectionExists200Response(time, status, result, )
        OpenAPI.validate_property(QdrantCollectionExists200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantCollectionExists200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantCollectionExists200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantCollectionExists200Response

const _property_types_QdrantCollectionExists200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantCollectionExistence", )
OpenAPI.property_type(::Type{ QdrantCollectionExists200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCollectionExists200Response[name]))}

function check_required(o::QdrantCollectionExists200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCollectionExists200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantCollectionExists200Response", :format, val, "float")
    end
end
