# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""RangeInterface

    QdrantRangeInterface(; value=nothing)
"""
mutable struct QdrantRangeInterface <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantDatetimeRange, QdrantRange }
    QdrantRangeInterface() = new()
    QdrantRangeInterface(value) = new(value)
end # type QdrantRangeInterface

function OpenAPI.property_type(::Type{ QdrantRangeInterface }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantRangeInterface, name)
end
