# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Batch_payloads_inner

    QdrantBatchPayloadsInner(; value=nothing)
"""
mutable struct QdrantBatchPayloadsInner <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Dict{String, Any} }
    QdrantBatchPayloadsInner() = new()
    QdrantBatchPayloadsInner(value) = new(value)
end # type QdrantBatchPayloadsInner

function OpenAPI.property_type(::Type{ QdrantBatchPayloadsInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantBatchPayloadsInner, name)
end
