# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CollectionsAliasesResponse

    QdrantCollectionsAliasesResponse(;
        aliases=nothing,
    )

    - aliases::Vector{QdrantAliasDescription}
"""
Base.@kwdef mutable struct QdrantCollectionsAliasesResponse <: OpenAPI.APIModel
    aliases::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantAliasDescription} }

    function QdrantCollectionsAliasesResponse(aliases, )
        OpenAPI.validate_property(QdrantCollectionsAliasesResponse, Symbol("aliases"), aliases)
        return new(aliases, )
    end
end # type QdrantCollectionsAliasesResponse

const _property_types_QdrantCollectionsAliasesResponse = Dict{Symbol,String}(Symbol("aliases")=>"Vector{QdrantAliasDescription}", )
OpenAPI.property_type(::Type{ QdrantCollectionsAliasesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCollectionsAliasesResponse[name]))}

function check_required(o::QdrantCollectionsAliasesResponse)
    o.aliases === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCollectionsAliasesResponse }, name::Symbol, val)
end
