# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Vector

    QdrantVector(; value=nothing)
"""
mutable struct QdrantVector <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantSparseVector, Vector{Float32}, Vector{Vector{Float32}} }
    QdrantVector() = new()
    QdrantVector(value) = new(value)
end # type QdrantVector

function OpenAPI.property_type(::Type{ QdrantVector }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantVector, name)
end
