# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PointsBatch

    QdrantPointsBatch(;
        batch=nothing,
        shard_key=nothing,
    )

    - batch::QdrantBatch
    - shard_key::QdrantShardKeySelector
"""
Base.@kwdef mutable struct QdrantPointsBatch <: OpenAPI.APIModel
    batch = nothing # spec type: Union{ Nothing, QdrantBatch }
    shard_key = nothing # spec type: Union{ Nothing, QdrantShardKeySelector }

    function QdrantPointsBatch(batch, shard_key, )
        OpenAPI.validate_property(QdrantPointsBatch, Symbol("batch"), batch)
        OpenAPI.validate_property(QdrantPointsBatch, Symbol("shard_key"), shard_key)
        return new(batch, shard_key, )
    end
end # type QdrantPointsBatch

const _property_types_QdrantPointsBatch = Dict{Symbol,String}(Symbol("batch")=>"QdrantBatch", Symbol("shard_key")=>"QdrantShardKeySelector", )
OpenAPI.property_type(::Type{ QdrantPointsBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPointsBatch[name]))}

function check_required(o::QdrantPointsBatch)
    o.batch === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPointsBatch }, name::Symbol, val)
end
