# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ClusterStatus_oneOf

    QdrantClusterStatusOneOf(;
        status=nothing,
    )

    - status::String
"""
Base.@kwdef mutable struct QdrantClusterStatusOneOf <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function QdrantClusterStatusOneOf(status, )
        OpenAPI.validate_property(QdrantClusterStatusOneOf, Symbol("status"), status)
        return new(status, )
    end
end # type QdrantClusterStatusOneOf

const _property_types_QdrantClusterStatusOneOf = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ QdrantClusterStatusOneOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantClusterStatusOneOf[name]))}

function check_required(o::QdrantClusterStatusOneOf)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantClusterStatusOneOf }, name::Symbol, val)
    if name === Symbol("status")
        OpenAPI.validate_param(name, "QdrantClusterStatusOneOf", :enum, val, ["disabled"])
    end
end
