# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""telemetry_200_response

    QdrantTelemetry200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantTelemetryData
"""
Base.@kwdef mutable struct QdrantTelemetry200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantTelemetryData }

    function QdrantTelemetry200Response(time, status, result, )
        OpenAPI.validate_property(QdrantTelemetry200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantTelemetry200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantTelemetry200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantTelemetry200Response

const _property_types_QdrantTelemetry200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantTelemetryData", )
OpenAPI.property_type(::Type{ QdrantTelemetry200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantTelemetry200Response[name]))}

function check_required(o::QdrantTelemetry200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantTelemetry200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantTelemetry200Response", :format, val, "float")
    end
end
