# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ShardKeySelector

    QdrantShardKeySelector(; value=nothing)
"""
mutable struct QdrantShardKeySelector <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantShardKey, Vector{QdrantShardKey} }
    QdrantShardKeySelector() = new()
    QdrantShardKeySelector(value) = new(value)
end # type QdrantShardKeySelector

function OpenAPI.property_type(::Type{ QdrantShardKeySelector }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantShardKeySelector, name)
end
