# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Filter_should
At least one of those conditions should match

    QdrantFilterShould(; value=nothing)
"""
mutable struct QdrantFilterShould <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantCondition, Vector{QdrantCondition} }
    QdrantFilterShould() = new()
    QdrantFilterShould(value) = new(value)
end # type QdrantFilterShould

function OpenAPI.property_type(::Type{ QdrantFilterShould }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantFilterShould, name)
end
