# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NestedCondition

    QdrantNestedCondition(;
        nested=nothing,
    )

    - nested::QdrantNested
"""
Base.@kwdef mutable struct QdrantNestedCondition <: OpenAPI.APIModel
    nested = nothing # spec type: Union{ Nothing, QdrantNested }

    function QdrantNestedCondition(nested, )
        OpenAPI.validate_property(QdrantNestedCondition, Symbol("nested"), nested)
        return new(nested, )
    end
end # type QdrantNestedCondition

const _property_types_QdrantNestedCondition = Dict{Symbol,String}(Symbol("nested")=>"QdrantNested", )
OpenAPI.property_type(::Type{ QdrantNestedCondition }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantNestedCondition[name]))}

function check_required(o::QdrantNestedCondition)
    o.nested === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantNestedCondition }, name::Symbol, val)
end
