# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TrackerStatus_oneOf_1

    QdrantTrackerStatusOneOf1(;
        error=nothing,
    )

    - error::String
"""
Base.@kwdef mutable struct QdrantTrackerStatusOneOf1 <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing

    function QdrantTrackerStatusOneOf1(error, )
        OpenAPI.validate_property(QdrantTrackerStatusOneOf1, Symbol("error"), error)
        return new(error, )
    end
end # type QdrantTrackerStatusOneOf1

const _property_types_QdrantTrackerStatusOneOf1 = Dict{Symbol,String}(Symbol("error")=>"String", )
OpenAPI.property_type(::Type{ QdrantTrackerStatusOneOf1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantTrackerStatusOneOf1[name]))}

function check_required(o::QdrantTrackerStatusOneOf1)
    o.error === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantTrackerStatusOneOf1 }, name::Symbol, val)
end
