# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateVectorsOperation

    QdrantUpdateVectorsOperation(;
        update_vectors=nothing,
    )

    - update_vectors::QdrantUpdateVectors
"""
Base.@kwdef mutable struct QdrantUpdateVectorsOperation <: OpenAPI.APIModel
    update_vectors = nothing # spec type: Union{ Nothing, QdrantUpdateVectors }

    function QdrantUpdateVectorsOperation(update_vectors, )
        OpenAPI.validate_property(QdrantUpdateVectorsOperation, Symbol("update_vectors"), update_vectors)
        return new(update_vectors, )
    end
end # type QdrantUpdateVectorsOperation

const _property_types_QdrantUpdateVectorsOperation = Dict{Symbol,String}(Symbol("update_vectors")=>"QdrantUpdateVectors", )
OpenAPI.property_type(::Type{ QdrantUpdateVectorsOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantUpdateVectorsOperation[name]))}

function check_required(o::QdrantUpdateVectorsOperation)
    o.update_vectors === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantUpdateVectorsOperation }, name::Symbol, val)
end
