# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""AnyVariants

    QdrantAnyVariants(; value=nothing)
"""
mutable struct QdrantAnyVariants <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Vector{Int64}, Vector{String} }
    QdrantAnyVariants() = new()
    QdrantAnyVariants(value) = new(value)
end # type QdrantAnyVariants

function OpenAPI.property_type(::Type{ QdrantAnyVariants }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantAnyVariants, name)
end
