# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NearestQuery

    QdrantNearestQuery(;
        nearest=nothing,
    )

    - nearest::QdrantVectorInput
"""
Base.@kwdef mutable struct QdrantNearestQuery <: OpenAPI.APIModel
    nearest = nothing # spec type: Union{ Nothing, QdrantVectorInput }

    function QdrantNearestQuery(nearest, )
        OpenAPI.validate_property(QdrantNearestQuery, Symbol("nearest"), nearest)
        return new(nearest, )
    end
end # type QdrantNearestQuery

const _property_types_QdrantNearestQuery = Dict{Symbol,String}(Symbol("nearest")=>"QdrantVectorInput", )
OpenAPI.property_type(::Type{ QdrantNearestQuery }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantNearestQuery[name]))}

function check_required(o::QdrantNearestQuery)
    o.nearest === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantNearestQuery }, name::Symbol, val)
end
