# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VersionInfo

    QdrantVersionInfo(;
        title=nothing,
        version=nothing,
        commit=nothing,
    )

    - title::String
    - version::String
    - commit::String
"""
Base.@kwdef mutable struct QdrantVersionInfo <: OpenAPI.APIModel
    title::Union{Nothing, String} = nothing
    version::Union{Nothing, String} = nothing
    commit::Union{Nothing, String} = nothing

    function QdrantVersionInfo(title, version, commit, )
        OpenAPI.validate_property(QdrantVersionInfo, Symbol("title"), title)
        OpenAPI.validate_property(QdrantVersionInfo, Symbol("version"), version)
        OpenAPI.validate_property(QdrantVersionInfo, Symbol("commit"), commit)
        return new(title, version, commit, )
    end
end # type QdrantVersionInfo

const _property_types_QdrantVersionInfo = Dict{Symbol,String}(Symbol("title")=>"String", Symbol("version")=>"String", Symbol("commit")=>"String", )
OpenAPI.property_type(::Type{ QdrantVersionInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantVersionInfo[name]))}

function check_required(o::QdrantVersionInfo)
    o.title === nothing && (return false)
    o.version === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantVersionInfo }, name::Symbol, val)
end
