# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""collection_cluster_info_200_response

    QdrantCollectionClusterInfo200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantCollectionClusterInfo
"""
Base.@kwdef mutable struct QdrantCollectionClusterInfo200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantCollectionClusterInfo }

    function QdrantCollectionClusterInfo200Response(time, status, result, )
        OpenAPI.validate_property(QdrantCollectionClusterInfo200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantCollectionClusterInfo200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantCollectionClusterInfo200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantCollectionClusterInfo200Response

const _property_types_QdrantCollectionClusterInfo200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantCollectionClusterInfo", )
OpenAPI.property_type(::Type{ QdrantCollectionClusterInfo200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCollectionClusterInfo200Response[name]))}

function check_required(o::QdrantCollectionClusterInfo200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCollectionClusterInfo200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantCollectionClusterInfo200Response", :format, val, "float")
    end
end
