# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IsEmptyCondition
Select points with empty payload for a specified field

    QdrantIsEmptyCondition(;
        is_empty=nothing,
    )

    - is_empty::QdrantPayloadField
"""
Base.@kwdef mutable struct QdrantIsEmptyCondition <: OpenAPI.APIModel
    is_empty = nothing # spec type: Union{ Nothing, QdrantPayloadField }

    function QdrantIsEmptyCondition(is_empty, )
        OpenAPI.validate_property(QdrantIsEmptyCondition, Symbol("is_empty"), is_empty)
        return new(is_empty, )
    end
end # type QdrantIsEmptyCondition

const _property_types_QdrantIsEmptyCondition = Dict{Symbol,String}(Symbol("is_empty")=>"QdrantPayloadField", )
OpenAPI.property_type(::Type{ QdrantIsEmptyCondition }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantIsEmptyCondition[name]))}

function check_required(o::QdrantIsEmptyCondition)
    o.is_empty === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantIsEmptyCondition }, name::Symbol, val)
end
