# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""get_collection_aliases_200_response

    QdrantGetCollectionAliases200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantCollectionsAliasesResponse
"""
Base.@kwdef mutable struct QdrantGetCollectionAliases200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantCollectionsAliasesResponse }

    function QdrantGetCollectionAliases200Response(time, status, result, )
        OpenAPI.validate_property(QdrantGetCollectionAliases200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantGetCollectionAliases200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantGetCollectionAliases200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantGetCollectionAliases200Response

const _property_types_QdrantGetCollectionAliases200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantCollectionsAliasesResponse", )
OpenAPI.property_type(::Type{ QdrantGetCollectionAliases200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantGetCollectionAliases200Response[name]))}

function check_required(o::QdrantGetCollectionAliases200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantGetCollectionAliases200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantGetCollectionAliases200Response", :format, val, "float")
    end
end
