# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayloadStorageType_oneOf

    QdrantPayloadStorageTypeOneOf(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct QdrantPayloadStorageTypeOneOf <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function QdrantPayloadStorageTypeOneOf(type, )
        OpenAPI.validate_property(QdrantPayloadStorageTypeOneOf, Symbol("type"), type)
        return new(type, )
    end
end # type QdrantPayloadStorageTypeOneOf

const _property_types_QdrantPayloadStorageTypeOneOf = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ QdrantPayloadStorageTypeOneOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPayloadStorageTypeOneOf[name]))}

function check_required(o::QdrantPayloadStorageTypeOneOf)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPayloadStorageTypeOneOf }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "QdrantPayloadStorageTypeOneOf", :enum, val, ["in_memory"])
    end
end
