# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayloadSelectorExclude

    QdrantPayloadSelectorExclude(;
        exclude=nothing,
    )

    - exclude::Vector{String} : Exclude this fields from returning payload
"""
Base.@kwdef mutable struct QdrantPayloadSelectorExclude <: OpenAPI.APIModel
    exclude::Union{Nothing, Vector{String}} = nothing

    function QdrantPayloadSelectorExclude(exclude, )
        OpenAPI.validate_property(QdrantPayloadSelectorExclude, Symbol("exclude"), exclude)
        return new(exclude, )
    end
end # type QdrantPayloadSelectorExclude

const _property_types_QdrantPayloadSelectorExclude = Dict{Symbol,String}(Symbol("exclude")=>"Vector{String}", )
OpenAPI.property_type(::Type{ QdrantPayloadSelectorExclude }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPayloadSelectorExclude[name]))}

function check_required(o::QdrantPayloadSelectorExclude)
    o.exclude === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPayloadSelectorExclude }, name::Symbol, val)
end
