# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DiscoverRequestBatch

    QdrantDiscoverRequestBatch(;
        searches=nothing,
    )

    - searches::Vector{QdrantDiscoverRequest}
"""
Base.@kwdef mutable struct QdrantDiscoverRequestBatch <: OpenAPI.APIModel
    searches::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantDiscoverRequest} }

    function QdrantDiscoverRequestBatch(searches, )
        OpenAPI.validate_property(QdrantDiscoverRequestBatch, Symbol("searches"), searches)
        return new(searches, )
    end
end # type QdrantDiscoverRequestBatch

const _property_types_QdrantDiscoverRequestBatch = Dict{Symbol,String}(Symbol("searches")=>"Vector{QdrantDiscoverRequest}", )
OpenAPI.property_type(::Type{ QdrantDiscoverRequestBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantDiscoverRequestBatch[name]))}

function check_required(o::QdrantDiscoverRequestBatch)
    o.searches === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantDiscoverRequestBatch }, name::Symbol, val)
end
