# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AbortShardTransfer

    QdrantAbortShardTransfer(;
        shard_id=nothing,
        to_peer_id=nothing,
        from_peer_id=nothing,
    )

    - shard_id::Int64
    - to_peer_id::Int64
    - from_peer_id::Int64
"""
Base.@kwdef mutable struct QdrantAbortShardTransfer <: OpenAPI.APIModel
    shard_id::Union{Nothing, Int64} = nothing
    to_peer_id::Union{Nothing, Int64} = nothing
    from_peer_id::Union{Nothing, Int64} = nothing

    function QdrantAbortShardTransfer(shard_id, to_peer_id, from_peer_id, )
        OpenAPI.validate_property(QdrantAbortShardTransfer, Symbol("shard_id"), shard_id)
        OpenAPI.validate_property(QdrantAbortShardTransfer, Symbol("to_peer_id"), to_peer_id)
        OpenAPI.validate_property(QdrantAbortShardTransfer, Symbol("from_peer_id"), from_peer_id)
        return new(shard_id, to_peer_id, from_peer_id, )
    end
end # type QdrantAbortShardTransfer

const _property_types_QdrantAbortShardTransfer = Dict{Symbol,String}(Symbol("shard_id")=>"Int64", Symbol("to_peer_id")=>"Int64", Symbol("from_peer_id")=>"Int64", )
OpenAPI.property_type(::Type{ QdrantAbortShardTransfer }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantAbortShardTransfer[name]))}

function check_required(o::QdrantAbortShardTransfer)
    o.shard_id === nothing && (return false)
    o.to_peer_id === nothing && (return false)
    o.from_peer_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantAbortShardTransfer }, name::Symbol, val)
    if name === Symbol("shard_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :format, val, "uint32")
    end
    if name === Symbol("shard_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :minimum, val, 0, false)
    end
    if name === Symbol("to_peer_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :format, val, "uint64")
    end
    if name === Symbol("to_peer_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :minimum, val, 0, false)
    end
    if name === Symbol("from_peer_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :format, val, "uint64")
    end
    if name === Symbol("from_peer_id")
        OpenAPI.validate_param(name, "QdrantAbortShardTransfer", :minimum, val, 0, false)
    end
end
