# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateShardingKeyOperation

    QdrantCreateShardingKeyOperation(;
        create_sharding_key=nothing,
    )

    - create_sharding_key::QdrantCreateShardingKey
"""
Base.@kwdef mutable struct QdrantCreateShardingKeyOperation <: OpenAPI.APIModel
    create_sharding_key = nothing # spec type: Union{ Nothing, QdrantCreateShardingKey }

    function QdrantCreateShardingKeyOperation(create_sharding_key, )
        OpenAPI.validate_property(QdrantCreateShardingKeyOperation, Symbol("create_sharding_key"), create_sharding_key)
        return new(create_sharding_key, )
    end
end # type QdrantCreateShardingKeyOperation

const _property_types_QdrantCreateShardingKeyOperation = Dict{Symbol,String}(Symbol("create_sharding_key")=>"QdrantCreateShardingKey", )
OpenAPI.property_type(::Type{ QdrantCreateShardingKeyOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCreateShardingKeyOperation[name]))}

function check_required(o::QdrantCreateShardingKeyOperation)
    o.create_sharding_key === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCreateShardingKeyOperation }, name::Symbol, val)
end
