# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""PayloadFieldSchema

    QdrantPayloadFieldSchema(; value=nothing)
"""
mutable struct QdrantPayloadFieldSchema <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantPayloadSchemaType, QdrantTextIndexParams }
    QdrantPayloadFieldSchema() = new()
    QdrantPayloadFieldSchema(value) = new(value)
end # type QdrantPayloadFieldSchema

function OpenAPI.property_type(::Type{ QdrantPayloadFieldSchema }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantPayloadFieldSchema, name)
end
