# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NamedVector
Dense vector data with name

    QdrantNamedVector(;
        name=nothing,
        vector=nothing,
    )

    - name::String : Name of vector data
    - vector::Vector{Float32} : Vector data
"""
Base.@kwdef mutable struct QdrantNamedVector <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    vector::Union{Nothing, Vector{Float32}} = nothing

    function QdrantNamedVector(name, vector, )
        OpenAPI.validate_property(QdrantNamedVector, Symbol("name"), name)
        OpenAPI.validate_property(QdrantNamedVector, Symbol("vector"), vector)
        return new(name, vector, )
    end
end # type QdrantNamedVector

const _property_types_QdrantNamedVector = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("vector")=>"Vector{Float32}", )
OpenAPI.property_type(::Type{ QdrantNamedVector }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantNamedVector[name]))}

function check_required(o::QdrantNamedVector)
    o.name === nothing && (return false)
    o.vector === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantNamedVector }, name::Symbol, val)
end
