# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""QueryInterface

    QdrantQueryInterface(; value=nothing)
"""
mutable struct QdrantQueryInterface <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantQuery, QdrantVectorInput }
    QdrantQueryInterface() = new()
    QdrantQueryInterface(value) = new(value)
end # type QdrantQueryInterface

function OpenAPI.property_type(::Type{ QdrantQueryInterface }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantQueryInterface, name)
end
