# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MatchExcept
Should have at least one value not matching the any given values

    QdrantMatchExcept(;
        except=nothing,
    )

    - except::QdrantAnyVariants
"""
Base.@kwdef mutable struct QdrantMatchExcept <: OpenAPI.APIModel
    except = nothing # spec type: Union{ Nothing, QdrantAnyVariants }

    function QdrantMatchExcept(except, )
        OpenAPI.validate_property(QdrantMatchExcept, Symbol("except"), except)
        return new(except, )
    end
end # type QdrantMatchExcept

const _property_types_QdrantMatchExcept = Dict{Symbol,String}(Symbol("except")=>"QdrantAnyVariants", )
OpenAPI.property_type(::Type{ QdrantMatchExcept }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantMatchExcept[name]))}

function check_required(o::QdrantMatchExcept)
    o.except === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantMatchExcept }, name::Symbol, val)
end
