# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ConsensusThreadStatus
Information about current consensus thread status

    QdrantConsensusThreadStatus(; value=nothing)
"""
mutable struct QdrantConsensusThreadStatus <: OpenAPI.OneOfAPIModel
    value::Any # Union{ QdrantConsensusThreadStatusOneOf, QdrantConsensusThreadStatusOneOf1, QdrantConsensusThreadStatusOneOf2 }
    QdrantConsensusThreadStatus() = new()
    QdrantConsensusThreadStatus(value) = new(value)
end # type QdrantConsensusThreadStatus

function OpenAPI.property_type(::Type{ QdrantConsensusThreadStatus }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantConsensusThreadStatus, name)
end
