# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WalConfigDiff

    QdrantWalConfigDiff(;
        wal_capacity_mb=nothing,
        wal_segments_ahead=nothing,
    )

    - wal_capacity_mb::Int64 : Size of a single WAL segment in MB
    - wal_segments_ahead::Int64 : Number of WAL segments to create ahead of actually used ones
"""
Base.@kwdef mutable struct QdrantWalConfigDiff <: OpenAPI.APIModel
    wal_capacity_mb::Union{Nothing, Int64} = nothing
    wal_segments_ahead::Union{Nothing, Int64} = nothing

    function QdrantWalConfigDiff(wal_capacity_mb, wal_segments_ahead, )
        OpenAPI.validate_property(QdrantWalConfigDiff, Symbol("wal_capacity_mb"), wal_capacity_mb)
        OpenAPI.validate_property(QdrantWalConfigDiff, Symbol("wal_segments_ahead"), wal_segments_ahead)
        return new(wal_capacity_mb, wal_segments_ahead, )
    end
end # type QdrantWalConfigDiff

const _property_types_QdrantWalConfigDiff = Dict{Symbol,String}(Symbol("wal_capacity_mb")=>"Int64", Symbol("wal_segments_ahead")=>"Int64", )
OpenAPI.property_type(::Type{ QdrantWalConfigDiff }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantWalConfigDiff[name]))}

function check_required(o::QdrantWalConfigDiff)
    true
end

function OpenAPI.validate_property(::Type{ QdrantWalConfigDiff }, name::Symbol, val)
    if name === Symbol("wal_capacity_mb")
        OpenAPI.validate_param(name, "QdrantWalConfigDiff", :format, val, "uint")
    end
    if name === Symbol("wal_capacity_mb")
        OpenAPI.validate_param(name, "QdrantWalConfigDiff", :minimum, val, 1, false)
    end
    if name === Symbol("wal_segments_ahead")
        OpenAPI.validate_param(name, "QdrantWalConfigDiff", :format, val, "uint")
    end
    if name === Symbol("wal_segments_ahead")
        OpenAPI.validate_param(name, "QdrantWalConfigDiff", :minimum, val, 0, false)
    end
end
