# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateFieldIndex

    QdrantCreateFieldIndex(;
        field_name=nothing,
        field_schema=nothing,
    )

    - field_name::String
    - field_schema::QdrantPayloadFieldSchema
"""
Base.@kwdef mutable struct QdrantCreateFieldIndex <: OpenAPI.APIModel
    field_name::Union{Nothing, String} = nothing
    field_schema = nothing # spec type: Union{ Nothing, QdrantPayloadFieldSchema }

    function QdrantCreateFieldIndex(field_name, field_schema, )
        OpenAPI.validate_property(QdrantCreateFieldIndex, Symbol("field_name"), field_name)
        OpenAPI.validate_property(QdrantCreateFieldIndex, Symbol("field_schema"), field_schema)
        return new(field_name, field_schema, )
    end
end # type QdrantCreateFieldIndex

const _property_types_QdrantCreateFieldIndex = Dict{Symbol,String}(Symbol("field_name")=>"String", Symbol("field_schema")=>"QdrantPayloadFieldSchema", )
OpenAPI.property_type(::Type{ QdrantCreateFieldIndex }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCreateFieldIndex[name]))}

function check_required(o::QdrantCreateFieldIndex)
    o.field_name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCreateFieldIndex }, name::Symbol, val)
end
