# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MultiVectorConfig

    QdrantMultiVectorConfig(;
        comparator=nothing,
    )

    - comparator::QdrantMultiVectorComparator
"""
Base.@kwdef mutable struct QdrantMultiVectorConfig <: OpenAPI.APIModel
    comparator = nothing # spec type: Union{ Nothing, QdrantMultiVectorComparator }

    function QdrantMultiVectorConfig(comparator, )
        OpenAPI.validate_property(QdrantMultiVectorConfig, Symbol("comparator"), comparator)
        return new(comparator, )
    end
end # type QdrantMultiVectorConfig

const _property_types_QdrantMultiVectorConfig = Dict{Symbol,String}(Symbol("comparator")=>"QdrantMultiVectorComparator", )
OpenAPI.property_type(::Type{ QdrantMultiVectorConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantMultiVectorConfig[name]))}

function check_required(o::QdrantMultiVectorConfig)
    o.comparator === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantMultiVectorConfig }, name::Symbol, val)
end
