# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""QueryRequest_prefetch
Sub-requests to perform first. If present, the query will be performed on the results of the prefetch(es).

    QdrantQueryRequestPrefetch(; value=nothing)
"""
mutable struct QdrantQueryRequestPrefetch <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantPrefetch, Vector{QdrantPrefetch} }
    QdrantQueryRequestPrefetch() = new()
    QdrantQueryRequestPrefetch(value) = new(value)
end # type QdrantQueryRequestPrefetch

function OpenAPI.property_type(::Type{ QdrantQueryRequestPrefetch }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantQueryRequestPrefetch, name)
end
