# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderBy

    QdrantOrderBy(;
        key=nothing,
        direction=nothing,
        start_from=nothing,
    )

    - key::String : Payload key to order by
    - direction::QdrantDirection
    - start_from::QdrantStartFrom
"""
Base.@kwdef mutable struct QdrantOrderBy <: OpenAPI.APIModel
    key::Union{Nothing, String} = nothing
    direction = nothing # spec type: Union{ Nothing, QdrantDirection }
    start_from = nothing # spec type: Union{ Nothing, QdrantStartFrom }

    function QdrantOrderBy(key, direction, start_from, )
        OpenAPI.validate_property(QdrantOrderBy, Symbol("key"), key)
        OpenAPI.validate_property(QdrantOrderBy, Symbol("direction"), direction)
        OpenAPI.validate_property(QdrantOrderBy, Symbol("start_from"), start_from)
        return new(key, direction, start_from, )
    end
end # type QdrantOrderBy

const _property_types_QdrantOrderBy = Dict{Symbol,String}(Symbol("key")=>"String", Symbol("direction")=>"QdrantDirection", Symbol("start_from")=>"QdrantStartFrom", )
OpenAPI.property_type(::Type{ QdrantOrderBy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantOrderBy[name]))}

function check_required(o::QdrantOrderBy)
    o.key === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantOrderBy }, name::Symbol, val)
end
