# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateOperations

    QdrantUpdateOperations(;
        operations=nothing,
    )

    - operations::Vector{QdrantUpdateOperation}
"""
Base.@kwdef mutable struct QdrantUpdateOperations <: OpenAPI.APIModel
    operations::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantUpdateOperation} }

    function QdrantUpdateOperations(operations, )
        OpenAPI.validate_property(QdrantUpdateOperations, Symbol("operations"), operations)
        return new(operations, )
    end
end # type QdrantUpdateOperations

const _property_types_QdrantUpdateOperations = Dict{Symbol,String}(Symbol("operations")=>"Vector{QdrantUpdateOperation}", )
OpenAPI.property_type(::Type{ QdrantUpdateOperations }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantUpdateOperations[name]))}

function check_required(o::QdrantUpdateOperations)
    o.operations === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantUpdateOperations }, name::Symbol, val)
end
