# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ShardKey

    QdrantShardKey(; value=nothing)
"""
mutable struct QdrantShardKey <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    QdrantShardKey() = new()
    QdrantShardKey(value) = new(value)
end # type QdrantShardKey

function OpenAPI.property_type(::Type{ QdrantShardKey }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantShardKey, name)
end
