# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""PayloadSchemaParams
Payload type with parameters

    QdrantPayloadSchemaParams(; value=nothing)
"""
mutable struct QdrantPayloadSchemaParams <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantBoolIndexParams, QdrantDatetimeIndexParams, QdrantFloatIndexParams, QdrantGeoIndexParams, QdrantIntegerIndexParams, QdrantKeywordIndexParams, QdrantTextIndexParams, QdrantUuidIndexParams }
    QdrantPayloadSchemaParams() = new()
    QdrantPayloadSchemaParams(value) = new(value)
end # type QdrantPayloadSchemaParams

function OpenAPI.property_type(::Type{ QdrantPayloadSchemaParams }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantPayloadSchemaParams, name)
end
