# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ShardTransferMethod
Methods for transferring a shard from one node to another.

    QdrantShardTransferMethod(; value=nothing)
"""
mutable struct QdrantShardTransferMethod <: OpenAPI.OneOfAPIModel
    value::Any # Union{ String }
    QdrantShardTransferMethod() = new()
    QdrantShardTransferMethod(value) = new(value)
end # type QdrantShardTransferMethod

function OpenAPI.property_type(::Type{ QdrantShardTransferMethod }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantShardTransferMethod, name)
end
