# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :QdrantTokenizerType)
    const QdrantTokenizerType = String
else
    @warn("Skipping redefinition of QdrantTokenizerType to String")
end
