# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MoveShard

    QdrantMoveShard(;
        shard_id=nothing,
        to_peer_id=nothing,
        from_peer_id=nothing,
        method=nothing,
    )

    - shard_id::Int64
    - to_peer_id::Int64
    - from_peer_id::Int64
    - method::QdrantShardTransferMethod
"""
Base.@kwdef mutable struct QdrantMoveShard <: OpenAPI.APIModel
    shard_id::Union{Nothing, Int64} = nothing
    to_peer_id::Union{Nothing, Int64} = nothing
    from_peer_id::Union{Nothing, Int64} = nothing
    method = nothing # spec type: Union{ Nothing, QdrantShardTransferMethod }

    function QdrantMoveShard(shard_id, to_peer_id, from_peer_id, method, )
        OpenAPI.validate_property(QdrantMoveShard, Symbol("shard_id"), shard_id)
        OpenAPI.validate_property(QdrantMoveShard, Symbol("to_peer_id"), to_peer_id)
        OpenAPI.validate_property(QdrantMoveShard, Symbol("from_peer_id"), from_peer_id)
        OpenAPI.validate_property(QdrantMoveShard, Symbol("method"), method)
        return new(shard_id, to_peer_id, from_peer_id, method, )
    end
end # type QdrantMoveShard

const _property_types_QdrantMoveShard = Dict{Symbol,String}(Symbol("shard_id")=>"Int64", Symbol("to_peer_id")=>"Int64", Symbol("from_peer_id")=>"Int64", Symbol("method")=>"QdrantShardTransferMethod", )
OpenAPI.property_type(::Type{ QdrantMoveShard }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantMoveShard[name]))}

function check_required(o::QdrantMoveShard)
    o.shard_id === nothing && (return false)
    o.to_peer_id === nothing && (return false)
    o.from_peer_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantMoveShard }, name::Symbol, val)
    if name === Symbol("shard_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :format, val, "uint32")
    end
    if name === Symbol("shard_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :minimum, val, 0, false)
    end
    if name === Symbol("to_peer_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :format, val, "uint64")
    end
    if name === Symbol("to_peer_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :minimum, val, 0, false)
    end
    if name === Symbol("from_peer_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :format, val, "uint64")
    end
    if name === Symbol("from_peer_id")
        OpenAPI.validate_param(name, "QdrantMoveShard", :minimum, val, 0, false)
    end
end
