# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""StartFrom

    QdrantStartFrom(; value=nothing)
"""
mutable struct QdrantStartFrom <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, Int64, ZonedDateTime }
    QdrantStartFrom() = new()
    QdrantStartFrom(value) = new(value)
end # type QdrantStartFrom

function OpenAPI.property_type(::Type{ QdrantStartFrom }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantStartFrom, name)
end
