# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AppBuildTelemetry

    QdrantAppBuildTelemetry(;
        name=nothing,
        version=nothing,
        features=nothing,
        system=nothing,
        startup=nothing,
    )

    - name::String
    - version::String
    - features::QdrantAppFeaturesTelemetry
    - system::QdrantRunningEnvironmentTelemetry
    - startup::ZonedDateTime
"""
Base.@kwdef mutable struct QdrantAppBuildTelemetry <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    version::Union{Nothing, String} = nothing
    features = nothing # spec type: Union{ Nothing, QdrantAppFeaturesTelemetry }
    system = nothing # spec type: Union{ Nothing, QdrantRunningEnvironmentTelemetry }
    startup::Union{Nothing, ZonedDateTime} = nothing

    function QdrantAppBuildTelemetry(name, version, features, system, startup, )
        OpenAPI.validate_property(QdrantAppBuildTelemetry, Symbol("name"), name)
        OpenAPI.validate_property(QdrantAppBuildTelemetry, Symbol("version"), version)
        OpenAPI.validate_property(QdrantAppBuildTelemetry, Symbol("features"), features)
        OpenAPI.validate_property(QdrantAppBuildTelemetry, Symbol("system"), system)
        OpenAPI.validate_property(QdrantAppBuildTelemetry, Symbol("startup"), startup)
        return new(name, version, features, system, startup, )
    end
end # type QdrantAppBuildTelemetry

const _property_types_QdrantAppBuildTelemetry = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("version")=>"String", Symbol("features")=>"QdrantAppFeaturesTelemetry", Symbol("system")=>"QdrantRunningEnvironmentTelemetry", Symbol("startup")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ QdrantAppBuildTelemetry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantAppBuildTelemetry[name]))}

function check_required(o::QdrantAppBuildTelemetry)
    o.name === nothing && (return false)
    o.version === nothing && (return false)
    o.startup === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantAppBuildTelemetry }, name::Symbol, val)
    if name === Symbol("startup")
        OpenAPI.validate_param(name, "QdrantAppBuildTelemetry", :format, val, "date-time")
    end
end
