# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ConsensusThreadStatus_oneOf_2

    QdrantConsensusThreadStatusOneOf2(;
        consensus_thread_status=nothing,
        err=nothing,
    )

    - consensus_thread_status::String
    - err::String
"""
Base.@kwdef mutable struct QdrantConsensusThreadStatusOneOf2 <: OpenAPI.APIModel
    consensus_thread_status::Union{Nothing, String} = nothing
    err::Union{Nothing, String} = nothing

    function QdrantConsensusThreadStatusOneOf2(consensus_thread_status, err, )
        OpenAPI.validate_property(QdrantConsensusThreadStatusOneOf2, Symbol("consensus_thread_status"), consensus_thread_status)
        OpenAPI.validate_property(QdrantConsensusThreadStatusOneOf2, Symbol("err"), err)
        return new(consensus_thread_status, err, )
    end
end # type QdrantConsensusThreadStatusOneOf2

const _property_types_QdrantConsensusThreadStatusOneOf2 = Dict{Symbol,String}(Symbol("consensus_thread_status")=>"String", Symbol("err")=>"String", )
OpenAPI.property_type(::Type{ QdrantConsensusThreadStatusOneOf2 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantConsensusThreadStatusOneOf2[name]))}

function check_required(o::QdrantConsensusThreadStatusOneOf2)
    o.consensus_thread_status === nothing && (return false)
    o.err === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantConsensusThreadStatusOneOf2 }, name::Symbol, val)
    if name === Symbol("consensus_thread_status")
        OpenAPI.validate_param(name, "QdrantConsensusThreadStatusOneOf2", :enum, val, ["stopped_with_err"])
    end
end
