# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayloadStorageType_oneOf_1

    QdrantPayloadStorageTypeOneOf1(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct QdrantPayloadStorageTypeOneOf1 <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function QdrantPayloadStorageTypeOneOf1(type, )
        OpenAPI.validate_property(QdrantPayloadStorageTypeOneOf1, Symbol("type"), type)
        return new(type, )
    end
end # type QdrantPayloadStorageTypeOneOf1

const _property_types_QdrantPayloadStorageTypeOneOf1 = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ QdrantPayloadStorageTypeOneOf1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPayloadStorageTypeOneOf1[name]))}

function check_required(o::QdrantPayloadStorageTypeOneOf1)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPayloadStorageTypeOneOf1 }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "QdrantPayloadStorageTypeOneOf1", :enum, val, ["on_disk"])
    end
end
