# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""create_field_index_200_response

    QdrantCreateFieldIndex200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantUpdateResult
"""
Base.@kwdef mutable struct QdrantCreateFieldIndex200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantUpdateResult }

    function QdrantCreateFieldIndex200Response(time, status, result, )
        OpenAPI.validate_property(QdrantCreateFieldIndex200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantCreateFieldIndex200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantCreateFieldIndex200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantCreateFieldIndex200Response

const _property_types_QdrantCreateFieldIndex200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantUpdateResult", )
OpenAPI.property_type(::Type{ QdrantCreateFieldIndex200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCreateFieldIndex200Response[name]))}

function check_required(o::QdrantCreateFieldIndex200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCreateFieldIndex200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantCreateFieldIndex200Response", :format, val, "float")
    end
end
