# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IntegerIndexParams

    QdrantIntegerIndexParams(;
        type=nothing,
        lookup=nothing,
        range=nothing,
        is_principal=nothing,
        on_disk=nothing,
    )

    - type::QdrantIntegerIndexType
    - lookup::Bool : If true - support direct lookups.
    - range::Bool : If true - support ranges filters.
    - is_principal::Bool : If true - use this key to organize storage of the collection data. This option assumes that this key will be used in majority of filtered requests.
    - on_disk::Bool : If true, store the index on disk. Default: false.
"""
Base.@kwdef mutable struct QdrantIntegerIndexParams <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, QdrantIntegerIndexType }
    lookup::Union{Nothing, Bool} = nothing
    range::Union{Nothing, Bool} = nothing
    is_principal::Union{Nothing, Bool} = nothing
    on_disk::Union{Nothing, Bool} = nothing

    function QdrantIntegerIndexParams(type, lookup, range, is_principal, on_disk, )
        OpenAPI.validate_property(QdrantIntegerIndexParams, Symbol("type"), type)
        OpenAPI.validate_property(QdrantIntegerIndexParams, Symbol("lookup"), lookup)
        OpenAPI.validate_property(QdrantIntegerIndexParams, Symbol("range"), range)
        OpenAPI.validate_property(QdrantIntegerIndexParams, Symbol("is_principal"), is_principal)
        OpenAPI.validate_property(QdrantIntegerIndexParams, Symbol("on_disk"), on_disk)
        return new(type, lookup, range, is_principal, on_disk, )
    end
end # type QdrantIntegerIndexParams

const _property_types_QdrantIntegerIndexParams = Dict{Symbol,String}(Symbol("type")=>"QdrantIntegerIndexType", Symbol("lookup")=>"Bool", Symbol("range")=>"Bool", Symbol("is_principal")=>"Bool", Symbol("on_disk")=>"Bool", )
OpenAPI.property_type(::Type{ QdrantIntegerIndexParams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantIntegerIndexParams[name]))}

function check_required(o::QdrantIntegerIndexParams)
    o.type === nothing && (return false)
    o.lookup === nothing && (return false)
    o.range === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantIntegerIndexParams }, name::Symbol, val)
end
