# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""VectorInput

    QdrantVectorInput(; value=nothing)
"""
mutable struct QdrantVectorInput <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantExtendedPointId, QdrantSparseVector, Vector{Float32}, Vector{Vector{Float32}} }
    QdrantVectorInput() = new()
    QdrantVectorInput(value) = new(value)
end # type QdrantVectorInput

function OpenAPI.property_type(::Type{ QdrantVectorInput }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantVectorInput, name)
end
