# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RecommendRequestBatch

    QdrantRecommendRequestBatch(;
        searches=nothing,
    )

    - searches::Vector{QdrantRecommendRequest}
"""
Base.@kwdef mutable struct QdrantRecommendRequestBatch <: OpenAPI.APIModel
    searches::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantRecommendRequest} }

    function QdrantRecommendRequestBatch(searches, )
        OpenAPI.validate_property(QdrantRecommendRequestBatch, Symbol("searches"), searches)
        return new(searches, )
    end
end # type QdrantRecommendRequestBatch

const _property_types_QdrantRecommendRequestBatch = Dict{Symbol,String}(Symbol("searches")=>"Vector{QdrantRecommendRequest}", )
OpenAPI.property_type(::Type{ QdrantRecommendRequestBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantRecommendRequestBatch[name]))}

function check_required(o::QdrantRecommendRequestBatch)
    o.searches === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantRecommendRequestBatch }, name::Symbol, val)
end
