# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MatchValue
Exact match of the given value

    QdrantMatchValue(;
        value=nothing,
    )

    - value::QdrantValueVariants
"""
Base.@kwdef mutable struct QdrantMatchValue <: OpenAPI.APIModel
    value = nothing # spec type: Union{ Nothing, QdrantValueVariants }

    function QdrantMatchValue(value, )
        OpenAPI.validate_property(QdrantMatchValue, Symbol("value"), value)
        return new(value, )
    end
end # type QdrantMatchValue

const _property_types_QdrantMatchValue = Dict{Symbol,String}(Symbol("value")=>"QdrantValueVariants", )
OpenAPI.property_type(::Type{ QdrantMatchValue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantMatchValue[name]))}

function check_required(o::QdrantMatchValue)
    o.value === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantMatchValue }, name::Symbol, val)
end
