# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RenameAliasOperation
Change alias to a new one

    QdrantRenameAliasOperation(;
        rename_alias=nothing,
    )

    - rename_alias::QdrantRenameAlias
"""
Base.@kwdef mutable struct QdrantRenameAliasOperation <: OpenAPI.APIModel
    rename_alias = nothing # spec type: Union{ Nothing, QdrantRenameAlias }

    function QdrantRenameAliasOperation(rename_alias, )
        OpenAPI.validate_property(QdrantRenameAliasOperation, Symbol("rename_alias"), rename_alias)
        return new(rename_alias, )
    end
end # type QdrantRenameAliasOperation

const _property_types_QdrantRenameAliasOperation = Dict{Symbol,String}(Symbol("rename_alias")=>"QdrantRenameAlias", )
OpenAPI.property_type(::Type{ QdrantRenameAliasOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantRenameAliasOperation[name]))}

function check_required(o::QdrantRenameAliasOperation)
    o.rename_alias === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantRenameAliasOperation }, name::Symbol, val)
end
