# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Filter_must
All conditions must match

    QdrantFilterMust(; value=nothing)
"""
mutable struct QdrantFilterMust <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantCondition, Vector{QdrantCondition} }
    QdrantFilterMust() = new()
    QdrantFilterMust(value) = new(value)
end # type QdrantFilterMust

function OpenAPI.property_type(::Type{ QdrantFilterMust }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantFilterMust, name)
end
