# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SetPayloadOperation

    QdrantSetPayloadOperation(;
        set_payload=nothing,
    )

    - set_payload::QdrantSetPayload
"""
Base.@kwdef mutable struct QdrantSetPayloadOperation <: OpenAPI.APIModel
    set_payload = nothing # spec type: Union{ Nothing, QdrantSetPayload }

    function QdrantSetPayloadOperation(set_payload, )
        OpenAPI.validate_property(QdrantSetPayloadOperation, Symbol("set_payload"), set_payload)
        return new(set_payload, )
    end
end # type QdrantSetPayloadOperation

const _property_types_QdrantSetPayloadOperation = Dict{Symbol,String}(Symbol("set_payload")=>"QdrantSetPayload", )
OpenAPI.property_type(::Type{ QdrantSetPayloadOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantSetPayloadOperation[name]))}

function check_required(o::QdrantSetPayloadOperation)
    o.set_payload === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantSetPayloadOperation }, name::Symbol, val)
end
