# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ClearPayloadOperation

    QdrantClearPayloadOperation(;
        clear_payload=nothing,
    )

    - clear_payload::QdrantPointsSelector
"""
Base.@kwdef mutable struct QdrantClearPayloadOperation <: OpenAPI.APIModel
    clear_payload = nothing # spec type: Union{ Nothing, QdrantPointsSelector }

    function QdrantClearPayloadOperation(clear_payload, )
        OpenAPI.validate_property(QdrantClearPayloadOperation, Symbol("clear_payload"), clear_payload)
        return new(clear_payload, )
    end
end # type QdrantClearPayloadOperation

const _property_types_QdrantClearPayloadOperation = Dict{Symbol,String}(Symbol("clear_payload")=>"QdrantPointsSelector", )
OpenAPI.property_type(::Type{ QdrantClearPayloadOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantClearPayloadOperation[name]))}

function check_required(o::QdrantClearPayloadOperation)
    o.clear_payload === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantClearPayloadOperation }, name::Symbol, val)
end
