# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Query

    QdrantQuery(; value=nothing)
"""
mutable struct QdrantQuery <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantContextQuery, QdrantDiscoverQuery, QdrantFusionQuery, QdrantNearestQuery, QdrantOrderByQuery, QdrantRecommendQuery, QdrantSampleQuery }
    QdrantQuery() = new()
    QdrantQuery(value) = new(value)
end # type QdrantQuery

function OpenAPI.property_type(::Type{ QdrantQuery }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantQuery, name)
end
