# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PointVectors

    QdrantPointVectors(;
        id=nothing,
        vector=nothing,
    )

    - id::QdrantExtendedPointId
    - vector::QdrantVectorStruct
"""
Base.@kwdef mutable struct QdrantPointVectors <: OpenAPI.APIModel
    id = nothing # spec type: Union{ Nothing, QdrantExtendedPointId }
    vector = nothing # spec type: Union{ Nothing, QdrantVectorStruct }

    function QdrantPointVectors(id, vector, )
        OpenAPI.validate_property(QdrantPointVectors, Symbol("id"), id)
        OpenAPI.validate_property(QdrantPointVectors, Symbol("vector"), vector)
        return new(id, vector, )
    end
end # type QdrantPointVectors

const _property_types_QdrantPointVectors = Dict{Symbol,String}(Symbol("id")=>"QdrantExtendedPointId", Symbol("vector")=>"QdrantVectorStruct", )
OpenAPI.property_type(::Type{ QdrantPointVectors }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPointVectors[name]))}

function check_required(o::QdrantPointVectors)
    o.id === nothing && (return false)
    o.vector === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPointVectors }, name::Symbol, val)
end
