# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayloadSelectorInclude

    QdrantPayloadSelectorInclude(;
        include=nothing,
    )

    - include::Vector{String} : Only include this payload keys
"""
Base.@kwdef mutable struct QdrantPayloadSelectorInclude <: OpenAPI.APIModel
    include::Union{Nothing, Vector{String}} = nothing

    function QdrantPayloadSelectorInclude(include, )
        OpenAPI.validate_property(QdrantPayloadSelectorInclude, Symbol("include"), include)
        return new(include, )
    end
end # type QdrantPayloadSelectorInclude

const _property_types_QdrantPayloadSelectorInclude = Dict{Symbol,String}(Symbol("include")=>"Vector{String}", )
OpenAPI.property_type(::Type{ QdrantPayloadSelectorInclude }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantPayloadSelectorInclude[name]))}

function check_required(o::QdrantPayloadSelectorInclude)
    o.include === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantPayloadSelectorInclude }, name::Symbol, val)
end
