# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DropShardingKeyOperation

    QdrantDropShardingKeyOperation(;
        drop_sharding_key=nothing,
    )

    - drop_sharding_key::QdrantDropShardingKey
"""
Base.@kwdef mutable struct QdrantDropShardingKeyOperation <: OpenAPI.APIModel
    drop_sharding_key = nothing # spec type: Union{ Nothing, QdrantDropShardingKey }

    function QdrantDropShardingKeyOperation(drop_sharding_key, )
        OpenAPI.validate_property(QdrantDropShardingKeyOperation, Symbol("drop_sharding_key"), drop_sharding_key)
        return new(drop_sharding_key, )
    end
end # type QdrantDropShardingKeyOperation

const _property_types_QdrantDropShardingKeyOperation = Dict{Symbol,String}(Symbol("drop_sharding_key")=>"QdrantDropShardingKey", )
OpenAPI.property_type(::Type{ QdrantDropShardingKeyOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantDropShardingKeyOperation[name]))}

function check_required(o::QdrantDropShardingKeyOperation)
    o.drop_sharding_key === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantDropShardingKeyOperation }, name::Symbol, val)
end
