# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ShardSnapshotLocation

    QdrantShardSnapshotLocation(; value=nothing)
"""
mutable struct QdrantShardSnapshotLocation <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ String }
    QdrantShardSnapshotLocation() = new()
    QdrantShardSnapshotLocation(value) = new(value)
end # type QdrantShardSnapshotLocation

function OpenAPI.property_type(::Type{ QdrantShardSnapshotLocation }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantShardSnapshotLocation, name)
end
