# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ScalarQuantization

    QdrantScalarQuantization(;
        scalar=nothing,
    )

    - scalar::QdrantScalarQuantizationConfig
"""
Base.@kwdef mutable struct QdrantScalarQuantization <: OpenAPI.APIModel
    scalar = nothing # spec type: Union{ Nothing, QdrantScalarQuantizationConfig }

    function QdrantScalarQuantization(scalar, )
        OpenAPI.validate_property(QdrantScalarQuantization, Symbol("scalar"), scalar)
        return new(scalar, )
    end
end # type QdrantScalarQuantization

const _property_types_QdrantScalarQuantization = Dict{Symbol,String}(Symbol("scalar")=>"QdrantScalarQuantizationConfig", )
OpenAPI.property_type(::Type{ QdrantScalarQuantization }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantScalarQuantization[name]))}

function check_required(o::QdrantScalarQuantization)
    o.scalar === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantScalarQuantization }, name::Symbol, val)
end
