# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IsNullCondition
Select points with null payload for a specified field

    QdrantIsNullCondition(;
        is_null=nothing,
    )

    - is_null::QdrantPayloadField
"""
Base.@kwdef mutable struct QdrantIsNullCondition <: OpenAPI.APIModel
    is_null = nothing # spec type: Union{ Nothing, QdrantPayloadField }

    function QdrantIsNullCondition(is_null, )
        OpenAPI.validate_property(QdrantIsNullCondition, Symbol("is_null"), is_null)
        return new(is_null, )
    end
end # type QdrantIsNullCondition

const _property_types_QdrantIsNullCondition = Dict{Symbol,String}(Symbol("is_null")=>"QdrantPayloadField", )
OpenAPI.property_type(::Type{ QdrantIsNullCondition }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantIsNullCondition[name]))}

function check_required(o::QdrantIsNullCondition)
    o.is_null === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantIsNullCondition }, name::Symbol, val)
end
