# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""NamedVectorStruct
Vector data separator for named and unnamed modes Unnamed mode:  { \&quot;vector\&quot;: [1.0, 2.0, 3.0] }  or named mode:  { \&quot;vector\&quot;: { \&quot;vector\&quot;: [1.0, 2.0, 3.0], \&quot;name\&quot;: \&quot;image-embeddings\&quot; } }

    QdrantNamedVectorStruct(; value=nothing)
"""
mutable struct QdrantNamedVectorStruct <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantNamedSparseVector, QdrantNamedVector, Vector{Float32} }
    QdrantNamedVectorStruct() = new()
    QdrantNamedVectorStruct(value) = new(value)
end # type QdrantNamedVectorStruct

function OpenAPI.property_type(::Type{ QdrantNamedVectorStruct }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantNamedVectorStruct, name)
end
