# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TextIndexParams

    QdrantTextIndexParams(;
        type=nothing,
        tokenizer=nothing,
        min_token_len=nothing,
        max_token_len=nothing,
        lowercase=nothing,
    )

    - type::QdrantTextIndexType
    - tokenizer::QdrantTokenizerType
    - min_token_len::Int64
    - max_token_len::Int64
    - lowercase::Bool : If true, lowercase all tokens. Default: true
"""
Base.@kwdef mutable struct QdrantTextIndexParams <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, QdrantTextIndexType }
    tokenizer = nothing # spec type: Union{ Nothing, QdrantTokenizerType }
    min_token_len::Union{Nothing, Int64} = nothing
    max_token_len::Union{Nothing, Int64} = nothing
    lowercase::Union{Nothing, Bool} = nothing

    function QdrantTextIndexParams(type, tokenizer, min_token_len, max_token_len, lowercase, )
        OpenAPI.validate_property(QdrantTextIndexParams, Symbol("type"), type)
        OpenAPI.validate_property(QdrantTextIndexParams, Symbol("tokenizer"), tokenizer)
        OpenAPI.validate_property(QdrantTextIndexParams, Symbol("min_token_len"), min_token_len)
        OpenAPI.validate_property(QdrantTextIndexParams, Symbol("max_token_len"), max_token_len)
        OpenAPI.validate_property(QdrantTextIndexParams, Symbol("lowercase"), lowercase)
        return new(type, tokenizer, min_token_len, max_token_len, lowercase, )
    end
end # type QdrantTextIndexParams

const _property_types_QdrantTextIndexParams = Dict{Symbol,String}(Symbol("type")=>"QdrantTextIndexType", Symbol("tokenizer")=>"QdrantTokenizerType", Symbol("min_token_len")=>"Int64", Symbol("max_token_len")=>"Int64", Symbol("lowercase")=>"Bool", )
OpenAPI.property_type(::Type{ QdrantTextIndexParams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantTextIndexParams[name]))}

function check_required(o::QdrantTextIndexParams)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantTextIndexParams }, name::Symbol, val)
    if name === Symbol("min_token_len")
        OpenAPI.validate_param(name, "QdrantTextIndexParams", :format, val, "uint")
    end
    if name === Symbol("min_token_len")
        OpenAPI.validate_param(name, "QdrantTextIndexParams", :minimum, val, 0, false)
    end
    if name === Symbol("max_token_len")
        OpenAPI.validate_param(name, "QdrantTextIndexParams", :format, val, "uint")
    end
    if name === Symbol("max_token_len")
        OpenAPI.validate_param(name, "QdrantTextIndexParams", :minimum, val, 0, false)
    end
end
