# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DropReplicaOperation

    QdrantDropReplicaOperation(;
        drop_replica=nothing,
    )

    - drop_replica::QdrantReplica
"""
Base.@kwdef mutable struct QdrantDropReplicaOperation <: OpenAPI.APIModel
    drop_replica = nothing # spec type: Union{ Nothing, QdrantReplica }

    function QdrantDropReplicaOperation(drop_replica, )
        OpenAPI.validate_property(QdrantDropReplicaOperation, Symbol("drop_replica"), drop_replica)
        return new(drop_replica, )
    end
end # type QdrantDropReplicaOperation

const _property_types_QdrantDropReplicaOperation = Dict{Symbol,String}(Symbol("drop_replica")=>"QdrantReplica", )
OpenAPI.property_type(::Type{ QdrantDropReplicaOperation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantDropReplicaOperation[name]))}

function check_required(o::QdrantDropReplicaOperation)
    o.drop_replica === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantDropReplicaOperation }, name::Symbol, val)
end
