# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CollectionsResponse

    QdrantCollectionsResponse(;
        collections=nothing,
    )

    - collections::Vector{QdrantCollectionDescription}
"""
Base.@kwdef mutable struct QdrantCollectionsResponse <: OpenAPI.APIModel
    collections::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QdrantCollectionDescription} }

    function QdrantCollectionsResponse(collections, )
        OpenAPI.validate_property(QdrantCollectionsResponse, Symbol("collections"), collections)
        return new(collections, )
    end
end # type QdrantCollectionsResponse

const _property_types_QdrantCollectionsResponse = Dict{Symbol,String}(Symbol("collections")=>"Vector{QdrantCollectionDescription}", )
OpenAPI.property_type(::Type{ QdrantCollectionsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantCollectionsResponse[name]))}

function check_required(o::QdrantCollectionsResponse)
    o.collections === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantCollectionsResponse }, name::Symbol, val)
end
