# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LocksOption

    QdrantLocksOption(;
        error_message=nothing,
        write=nothing,
    )

    - error_message::String
    - write::Bool
"""
Base.@kwdef mutable struct QdrantLocksOption <: OpenAPI.APIModel
    error_message::Union{Nothing, String} = nothing
    write::Union{Nothing, Bool} = nothing

    function QdrantLocksOption(error_message, write, )
        OpenAPI.validate_property(QdrantLocksOption, Symbol("error_message"), error_message)
        OpenAPI.validate_property(QdrantLocksOption, Symbol("write"), write)
        return new(error_message, write, )
    end
end # type QdrantLocksOption

const _property_types_QdrantLocksOption = Dict{Symbol,String}(Symbol("error_message")=>"String", Symbol("write")=>"Bool", )
OpenAPI.property_type(::Type{ QdrantLocksOption }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantLocksOption[name]))}

function check_required(o::QdrantLocksOption)
    o.write === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantLocksOption }, name::Symbol, val)
end
