# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""get_collections_200_response

    QdrantGetCollections200Response(;
        time=nothing,
        status=nothing,
        result=nothing,
    )

    - time::Float32 : Time spent to process this request
    - status::String
    - result::QdrantCollectionsResponse
"""
Base.@kwdef mutable struct QdrantGetCollections200Response <: OpenAPI.APIModel
    time::Union{Nothing, Float32} = nothing
    status::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, QdrantCollectionsResponse }

    function QdrantGetCollections200Response(time, status, result, )
        OpenAPI.validate_property(QdrantGetCollections200Response, Symbol("time"), time)
        OpenAPI.validate_property(QdrantGetCollections200Response, Symbol("status"), status)
        OpenAPI.validate_property(QdrantGetCollections200Response, Symbol("result"), result)
        return new(time, status, result, )
    end
end # type QdrantGetCollections200Response

const _property_types_QdrantGetCollections200Response = Dict{Symbol,String}(Symbol("time")=>"Float32", Symbol("status")=>"String", Symbol("result")=>"QdrantCollectionsResponse", )
OpenAPI.property_type(::Type{ QdrantGetCollections200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantGetCollections200Response[name]))}

function check_required(o::QdrantGetCollections200Response)
    true
end

function OpenAPI.validate_property(::Type{ QdrantGetCollections200Response }, name::Symbol, val)
    if name === Symbol("time")
        OpenAPI.validate_param(name, "QdrantGetCollections200Response", :format, val, "float")
    end
end
