# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""AliasOperations
Group of all the possible operations related to collection aliases

    QdrantAliasOperations(; value=nothing)
"""
mutable struct QdrantAliasOperations <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ QdrantCreateAliasOperation, QdrantDeleteAliasOperation, QdrantRenameAliasOperation }
    QdrantAliasOperations() = new()
    QdrantAliasOperations(value) = new(value)
end # type QdrantAliasOperations

function OpenAPI.property_type(::Type{ QdrantAliasOperations }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(QdrantAliasOperations, name)
end
