# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :QdrantFusion)
    const QdrantFusion = String
else
    @warn("Skipping redefinition of QdrantFusion to String")
end
