# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MatchText
Full-text match of the strings.

    QdrantMatchText(;
        text=nothing,
    )

    - text::String
"""
Base.@kwdef mutable struct QdrantMatchText <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing

    function QdrantMatchText(text, )
        OpenAPI.validate_property(QdrantMatchText, Symbol("text"), text)
        return new(text, )
    end
end # type QdrantMatchText

const _property_types_QdrantMatchText = Dict{Symbol,String}(Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ QdrantMatchText }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantMatchText[name]))}

function check_required(o::QdrantMatchText)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantMatchText }, name::Symbol, val)
end
