# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WebApiTelemetry

    QdrantWebApiTelemetry(;
        responses=nothing,
    )

    - responses::Dict{String, Dict{String, QdrantOperationDurationStatistics}}
"""
Base.@kwdef mutable struct QdrantWebApiTelemetry <: OpenAPI.APIModel
    responses::Union{Nothing, Dict{String, Dict{String, QdrantOperationDurationStatistics}}} = nothing

    function QdrantWebApiTelemetry(responses, )
        OpenAPI.validate_property(QdrantWebApiTelemetry, Symbol("responses"), responses)
        return new(responses, )
    end
end # type QdrantWebApiTelemetry

const _property_types_QdrantWebApiTelemetry = Dict{Symbol,String}(Symbol("responses")=>"Dict{String, Dict{String, QdrantOperationDurationStatistics}}", )
OpenAPI.property_type(::Type{ QdrantWebApiTelemetry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QdrantWebApiTelemetry[name]))}

function check_required(o::QdrantWebApiTelemetry)
    o.responses === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ QdrantWebApiTelemetry }, name::Symbol, val)
end
